---
title: "05_human_coders_reliability"
author: "Dr. Joscelin Rocha-Hidalgo"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE)
```

# Setup

## Install and load packages

```{r}
# Installing pacman and loading packages
if (!("pacman" %in% installed.packages()[, ])) {
  install.packages("pacman")
}
pacman::p_load(tidyverse, irr)

source("http://pcwww.liv.ac.uk/~william/R/crosstab.r")
```

# Per Frame

## BFFs Study

### Load csv

```{r}
bffs <- read_csv("../data/bffs_validation_data.csv")

bffs_reliability <- bffs |> 
  filter(!is.na(hand_code_rel))
```

### Kappa reliability
```{r}
kappa2(bffs_reliability[,c("hand_code","hand_code_rel")], "unweighted")
crosstab(bffs_reliability, row.vars = "hand_code", col.vars = "hand_code_rel", type = "f")

```
## PCAT Study

### Load csv

```{r}
pcat <- read_csv("../data/pcat_validation_data.csv") 
pcat_reliability <- pcat |> 
  filter(!is.na(hand_code_rel))
```

### AB: Kappa reliability
```{r}
kappa2(pcat_reliability[,c("hand_code","hand_code_rel")], "unweighted")
crosstab(pcat_reliability, row.vars = "hand_code", col.vars = "hand_code_rel", type = "f")
```


