---
title: "pcat_compile_data"
author: "Marisa Lytle"
date: "2025-02-13"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

#Setting the root directory
knitr::opts_knit$set(root.dir = 'C:/Users/maris/OneDrive - The Pennsylvania State University/Research Projects/CV_MET/AP Special Issue')
```

```{r}
#Installing pacman and loading packages
if (!("pacman" %in% installed.packages()[,])) {
    install.packages("pacman")
}
pacman::p_load(readxl,tidyverse,fs)
```

```{r}
input_files <- dir_ls("./data/pcat", regexp = "\\.csv$")
input_data <- input_files |>
  map_dfr(read_csv, .id = "id") |>
  mutate(id = str_sub(id, start = 13, end = 19)) |>
  separate(id, c("dyad", "subject"),remove=FALSE) |>
  group_by(id,task) |>
  mutate(time = rep(seq(length(id)/29), 
                     length.out = length(id), each = 30)) |>
  select(-c(Track_ID)) |>
  ungroup()

#Fix frame rate for 11060_C
fix <- filter(input_data, id == "11060_C") |> 
  group_by(id,task) |>
  mutate(time = rep(seq(length(id)/28), 
                     length.out = length(id), each = 29)) |>
  ungroup()

input_data <- input_data |>
  filter(id != "11060_C") |>
  full_join(fix)


aoi <- input_data |>
  group_by(id,task, time, Code) |>
  summarise(aoiN = n()) |>
  ungroup() |>
  group_by(id,task, time) |>
  filter(aoiN == max(aoiN)) |>
  select(-aoiN) |>
  ungroup()

# Check for duplicates
aoi |>
  group_by(id,task, time) |>
  filter(duplicated(time))

# Remove duplicates
aoi2 <- aoi |>
  group_by(id,task, time) |>
  slice_head() |>
  ungroup()  |>
  rename(Code_sec = Code)

aoi_h <- input_data |>
  group_by(id,task, time, hand_code) |>
  summarise(aoiN = n()) |>
  ungroup() |>
  group_by(id,task, time) |>
  filter(aoiN == max(aoiN)) |>
  select(-aoiN) |>
  ungroup()

# Check for duplicates
aoi_h |>
  group_by(id,task, time) |>
  filter(duplicated(time))

# Remove duplicates
aoi2_h <- aoi_h |>
  group_by(id,task, time) |>
  slice_head() |>
  ungroup() |>
  rename(hand_code_sec = hand_code)

data <- left_join(input_data,aoi2) |>
  left_join(aoi2_h)

```

#Add reliability
```{r}
input_files <- dir_ls("./data/pcat/reliability", regexp = "\\.csv$")
input_data <- input_files |>
  map_dfr(read_csv, .id = "id") |>
  mutate(id = str_sub(id, start = 25, end = 31)) |>
  separate(id, c("dyad", "subject"),remove=FALSE) |>
  group_by(id,task) |>
  mutate(time = rep(seq(length(id)/29), 
                     length.out = length(id), each = 30)) |>
  select(-c(Track_ID)) |>
  ungroup()

#Fix frame rate for 11060_C
fix <- filter(input_data, id == "11060_C") |> 
  group_by(id,task) |>
  mutate(time = rep(seq(length(id)/28), 
                     length.out = length(id), each = 29)) |>
  ungroup()

input_data <- input_data |>
  filter(id != "11060_C") |>
  full_join(fix)



aoi <- input_data |>
  group_by(id,task, time, Code) |>
  summarise(aoiN = n()) |>
  ungroup() |>
  group_by(id,task, time) |>
  filter(aoiN == max(aoiN)) |>
  select(-aoiN) |>
  ungroup()

# Check for duplicates
aoi |>
  group_by(id,task, time) |>
  filter(duplicated(time))

# Remove duplicates
aoi2 <- aoi |>
  group_by(id,task, time) |>
  slice_head() |>
  ungroup()  |>
  rename(Code_sec = Code)

aoi_h <- input_data |>
  group_by(id,task, time, hand_code) |>
  summarise(aoiN = n()) |>
  ungroup() |>
  group_by(id,task, time) |>
  filter(aoiN == max(aoiN)) |>
  select(-aoiN) |>
  ungroup()

# Check for duplicates
aoi_h |>
  group_by(id,task, time) |>
  filter(duplicated(time))

# Remove duplicates
aoi2_h <- aoi_h |>
  group_by(id,task, time) |>
  slice_head() |>
  ungroup() |>
  rename(hand_code_sec = hand_code)

data_rel <- left_join(input_data,aoi2) |>
  left_join(aoi2_h) |>
  rename(hand_code_rel = hand_code,
         hand_code_sec_rel = hand_code_sec)
```

```{r}
data <- full_join(data,data_rel)

write.csv(data,"./data/pcat_validation_data.csv", row.names = FALSE)
```

